item {
  id: 1
  name: 'sol'
}

item {
  id: 2
  name: 'indio'
}

item {
  id: 3
  name: 'xx'
}

item {
  id: 4
  name: 'miller'
}

item {
  id: 5
  name: 'bohemiaP'
}

item {
  id: 6
  name: 'strongbowA'
}

item {
  id: 7
  name: 'strongbowR'
}

item {
  id: 8
  name: 'heineken'
}

item {
  id: 9
  name: 'carta'
}

item {
  id: 10
  name: 'indioC'
}

item {
  id: 11
  name: 'tecateC'
}

item {
  id: 12
  name: 'tecate'
}

item {
  id: 13
  name: 'heineken6'
}
